### ISSUE TITLE
Endless loop in master branch when NOT using the ambiguous flag.

### ISSUE THREAD

**Issue by malc0mn** [roderik/pwgen-php#13]
The commit in issue #3 has caused the master branch to be broken: generating a password by creating a new pwgen instance **without params** and calling the generate method will trigger an endless loop:
```php
<?php

$pwgen = new PWGen();
$pass = $pwgen->generate();
var_dump($pass);
```
This **will** work:
```php
<?php

$pwgen = new PWGen();
$pwgen->setAmbiguous(true);
$pass = $pwgen->generate();
var_dump($pass);
```

I've been comparing the **perfectly functional 0.1.7 tag** with the master branch and the **only functional difference** is the commit in #3. I'm not sure yet as to what the exact cause is, but I do know it's this piece of code :-)

```diff
diff --git a/PWGen.php b/PWGen.php
index a082f40..496878b 100644
--- a/PWGen.php
+++ b/PWGen.php
@@ -250,9 +250,7 @@ class PWGen
                 // Handle PW_UPPERS
                 if ($this->pwgen_flags & self::PW_UPPERS) {
                     if (($first || $flags & self::CONSONANT) &&
-                        (self::my_rand(0, 9) < 2) &&
-                        ($this->pwgen_flags & self::PW_AMBIGUOUS) &&
-                        strpos(self::$pw_ambiguous, strtoupper($this->password[$c])) === false) {
+                        (self::my_rand(0, 9) < 2)) {
                         $this->password[$c] = strtoupper($this->password[$c]);
                         $feature_flags &= ~self::PW_UPPERS;
```

**Comment by pips-** [comment]
Oh, my bad, I can now spot the error.

The loop attempt to produce an uppercase character, but it can only do so if the scanned char is not in the ambiguous set AND the ambiguous flag is true. The logic between these two conditions should be an OR : Thus it produce an uppercase char if  the flag allow it OR if the char is not litigious.

I will propose a simple fix later.

I'm also wondering what would happen if none of the current characters is eligible to become an uppercase char according to the ambiguous set. :\

**Comment by malc0mn** [comment]
@pips- Cool! #14 was just now merged to master, so you can instantly use the test suite to validate your fix when it's ready ;-)

**Comment by pips-** [comment]
Great! thanks for the tests.

I pulled and try to validate my modification against tests, but it failed on testGenerateAmbiguous because this test construct PWGen with $capitalize  set to false, but ambiguous characters only apear as uppercase ones.

I propose to change this test to allow uppercase characters, do you agree?

**Comment by pips-** [comment]
Hm, so I locally tried this solution, due to the random nature of password generated, the tests may pass or fail sometime.

Can't we mock up the random generator in tests?

**Comment by malc0mn** [comment]
@pips- I wrote the tests quite quickly so **some of those might actually be wrong!** But the Ambiguous test never passed as the regex never detected the ambiguous characters in the generated password.

I assumed it was due to the 'problematic' fix in #3 but I'm not sure...

If ambiguous **must** have uppercase chars, then the `setAmbiguous()` method should be adjusted to also set the `PW_UPPERS` flag as well, IMHO...

**Comment by malc0mn** [comment]
Oh, and then the `hasAmbiguous()` also needs an update ofcourse, but you would have noticed that in the test failing in a different spot

**Comment by malc0mn** [comment]
Something like this (**I'm not sure about the removal of the flags though!**)
```php
<?php

    public function setAmbiguous($ambiguous)
    {
        if ($ambiguous) {
            $this->pwgen_flags |= self::PW_AMBIGUOUS | self::PW_UPPERS;
        } else {
            $this->pwgen_flags &= ~self::PW_AMBIGUOUS;
            $this->pwgen_flags &= ~self::PW_UPPERS;
        }
        return $this;
    }

    public function hasAmbiguous()
    {
        return ($this->pwgen_flags & self::PW_AMBIGUOUS) === self::PW_AMBIGUOUS &&
            ($this->pwgen_flags & self::PW_AMBIGUOUS) === self::PW_UPPERS
        ;
    }

```

We should only adjust the test if the test is wrong, but judging from your first comment about the failing test, I think the setter is wrong...

**Comment by pips-** [comment]
Hm, in fact I think we can't test ambiguous this way.

The ambiguous flag is not like the others, symbols, digits, uppers, lowers & vowels, when active, will enforced the generations of such characters, but ambiguous will only allow it or not. Do you see what I mean?

I think this can't really be test as-is and expected there is at least one ambiguous character when set.

One way I see it, would be to mock up the random generator, forcing ambiguous characters generation and verify that no one pass through to the final password. 

What do you think about this?

**Comment by malc0mn** [comment]
@pips- Your explanation is very clear and indeed describes the problem with testing the Ambiguous output. The only proper way would indeed be to force the generation of ambiguous characters and check that they are present.
In all other tests, an additional assert should be added to check that **no** ambiguous characters are present.

I think that would cover it...
