### ISSUE TITLE
Version bump

### ISSUE THREAD

**Issue by pips-** [roderik/pwgen-php#17]
Would you mind making a new minor version please?

I would need last fixes as composer dependency.

**Comment by roderik** [comment]
Done

**Comment by pips-** [comment]
Thanks for the new version, but I can't find it on [packagist.org/roderik/pwgen-php](https://packagist.org/packages/roderik/pwgen-php), can you update the package there or enable the hook on github please?

**Comment by roderik** [comment]
I’m totally out of the PHP scene, care to take over as maintainer?

*Roderik van der Veer*
Founder & CTO

*SettleMint* - https://settlemint.com

https://twitter.com/r0derik
https://be.linkedin.com/in/roderik

**Comment by pips-** [comment]
Yes, no problem. I'm not sure about the right process, be it on github or packagist, but if I can be of any help!

**Comment by pips-** [comment]
Many thanks for the access to the github repository. :)

I'm sorry to bother you again with this, particularly knowing you are not into PHP anymore, but I'm missing just a few little bits to update the package for the composer/packagist system.

Can you have look at the [packagist website](https://packagist.org/) to also allow me to update the package there please?
