### ISSUE TITLE
Closing PHP-tag at the end of a file

### ISSUE THREAD

**Issue by test4serge** [roderik/pwgen-php#8]
Please remove closing PHP-tag at the end of a file - just remove last line, that contain "?>" from PWGen.php

> The closing tag of a PHP block at the end of a file is optional, and in some cases omitting it is helpful when using include or require, so unwanted whitespace will not occur at the end of files, and you will still be able to add headers to the response later. It is also handy if you use output buffering, and would not like to see added unwanted whitespace at the end of the parts generated by the included files. 

http://php.net/basic-syntax.instruction-separation

**Comment by roderik** [comment]
I'll merge a PR 😃
